{
	"version": 1576290719,
	"fileList": [
		"data.js",
		"c2runtime.js",
		"jquery-2.1.1.min.js",
		"offlineClient.js",
		"images/objetossolidos.png",
		"images/player-sheet0.png",
		"images/player_animation-sheet0.png",
		"images/tiledbackground.png",
		"images/gameoverscreen.png",
		"images/scoreplacar.png",
		"images/fundo_telainicial.png",
		"images/play-sheet0.png",
		"images/sprite2-sheet0.png",
		"images/tiledbackground2.png",
		"images/acido1.png",
		"images/tiledbackground4.png",
		"images/skipbutton-sheet0.png",
		"images/inst.png",
		"images/sprite-sheet0.png",
		"images/sprite3-sheet0.png",
		"media/gotta go fast.ogg",
		"media/você é a vergonha da profissão.ogg",
		"icon-16.png",
		"icon-32.png",
		"icon-114.png",
		"icon-128.png",
		"icon-256.png",
		"loading-logo.png",
		"intro.mp4"
	]
}